name: KtLint
on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlint.yml"
jobs:
  build:
    name: "KtLint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v2"
